language: python
python: 3.5
sudo: required
dist: trusty
services: docker
sudo: required

env:
  global:
    - secure: PBcwrLg4ZwVi9Gw25Q2adNd0uK+NCqFSiYl+ZuumkEXs4NQBbSXVd719wrWKUFdIqBy+h9ETo4Vsz/QsTZzI2mSG4zqTkm+oUxMW1tJxYEeKZvCo7GfZ883VlKFgdqvh6iouEvHSjfGbwc5cUp98CbjgI5ni01vGpDQh2hgokkI=
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - NP_BUILD_DEP="numpy==1.7.1"
    - NP_TEST_DEP="numpy==1.7.1"

matrix:
  exclude:
      - python: 3.5
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - TOXENV=py27
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
        - TOXENV=py27
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - TOXENV=py27
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
        - TOXENV=py27
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.4
        - TOXENV=py34
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.4
        - TOXENV=py34
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - TOXENV=py35
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - TOXENV=py35
        - PLAT=i686
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=2.7
        - TOXENV=py27
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=3.4
        - TOXENV=py34
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=3.5
        - TOXENV=py35

before_install:
  - (git clone https://github.com/matthew-brett/multibuild.git && cd multibuild && git checkout d7ba4ae)
  - TEST_DEPENDS="nose"
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install
        
install:
  - build_wheel . $PLAT

script:
  - install_run $PLAT

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: feature/auto-wheel
#    tags: true
