language: python
python: 3.5
sudo: required
dist: trusty
services: docker
sudo: required

env:
  global:
    - secure: "OyCxLHV86t/4gTOyXdmQa4ux3GYPPS5PCsr/mAfQkGaRPPwdmuSqt/3DZVB9OuWmVn0I8/7I+jNHiLdW7TkHYeDgJzR3cZM6yy/Ear7igV+zlGJStCpCiBX9kzOxxShtZqTWq48ET8eAhlEF+cBXg1IBKv5orQrhxon8JszFHfM="
    - secure: "Ao68oM4+c+uV3MYAsR3KNpKVpVDOnCoCRhF0CPHh0sYEcFH7EM5wCy5fzYSo8iThcV4pCuzJ/ThMtijNDmVoAH7xPfanJL3IMpq0urp8AVruv5vjKzG40G3BK0nMCKDUBwPSN1e3YCl5tBxutqW7K95CrQ4tY1pL6I1+IU/w5nM="
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - NP_BUILD_DEP="numpy==1.7.1"
    - NP_TEST_DEP="numpy==1.7.1"

matrix:
  exclude:
      - python: 3.5
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.4
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.4
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - TOXENV=py35
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=3.4
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=3.5

before_install:
  - (git clone https://github.com/matthew-brett/multibuild.git && cd multibuild && git checkout d7ba4ae)
  - TEST_DEPENDS="nose"
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  # why no tox? tox runs in its own virtual env it seems that `which glpsol` doesn't work there 
  - build_wheel . $PLAT

before_cache:
  - set +e

script:
  - install_run $PLAT

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master
    tags: true
