language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get install libglpk-dev swig glpk-utils
install:
  - pip install nose
  - python setup.py install
# # command to run tests
script: python setup.py nosetests